build:
  maxIssues: 0
  excludeCorrectable: false

config:
  validation: true
  warningsAsErrors: false

comments:
  active: true
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false

complexity:
  active: true
  CyclomaticComplexMethod:
    active: true
    threshold: 15
    ignoreAnnotated: ['Composable']
  LargeClass:
    active: true
    threshold: 600
  LongMethod:
    active: true
    threshold: 60
  LongParameterList:
    active: true
    functionThreshold: 8
    constructorThreshold: 8
    ignoreDefaultParameters: true
    ignoreDataClasses: true
    ignoreAnnotated: ['Composable']
  TooManyFunctions:
    active: true
    thresholdInFiles: 20
    thresholdInClasses: 20
    ignoreAnnotated: ['Composable']

coroutines:
  active: true
  GlobalCoroutineUsage:
    active: true
  SuspendFunWithFlowReturnType:
    active: true

empty-blocks:
  active: true
  EmptyCatchBlock:
    active: true
    allowedExceptionNameRegex: '_|(ignore|expected).*'

exceptions:
  active: true
  TooGenericExceptionCaught:
    active: true
    allowedExceptionNameRegex: '_|(ignore|expected).*'
  TooGenericExceptionThrown:
    active: true

naming:
  active: true
  FunctionNaming:
    active: true
    ignoreAnnotated: ['Composable']
  PackageNaming:
    active: true
    packagePattern: '[a-z]+(\.[a-z][A-Za-z0-9]*)*'

performance:
  active: true
  SpreadOperator:
    active: false

potential-bugs:
  active: true
  IgnoredReturnValue:
    active: true
  UnnecessaryNotNullOperator:
    active: true
  UnnecessarySafeCall:
    active: true

style:
  active: true
  ForbiddenComment:
    active: true
    values:
      - reason: 'Aufräumen vor Merge!'
        value: 'STOPSHIP:'
  MaxLineLength:
    active: true
    maxLineLength: 140
    excludePackageStatements: true
    excludeImportStatements: true
  MayBeConst:
    active: true
  ModifierOrder:
    active: true
  NewLineAtEndOfFile:
    active: true
  UnusedPrivateClass:
    active: true
  UnusedPrivateMember:
    active: true
  VarCouldBeVal:
    active: true
  WildcardImport:
    active: true
    excludeImports:
      - 'java.util.*'
      - 'androidx.compose.ui.*'
      - 'androidx.compose.material3.*'
      - 'androidx.compose.foundation.*'
      - 'androidx.compose.runtime.*'
